//------------------------------------------------//
// Copyright (c) 2026 Nebula-Ray42.               //
// SPDX-License-Identifier: BSD-2-Clause-Patent   //
//------------------------------------------------//

#include <expected>
#include <format>
#include <string>

#include "generator_core.h"

namespace vanta::slang_generator {

    std::expected<std::string, std::string> generate_cpp_bindings(const ResourceBindingsSoA& soa_data) {
        if (soa_data.names.empty()) {
            return std::unexpected("No resources to generate.");
        }

        std::string out;

        out += std::format("// ==========================================\n");
        out += std::format("// Auto-generated by Rey Engine Slang Generator\n");
        out += std::format("// DO NOT EDIT DIRECTLY\n");
        out += std::format("// ==========================================\n");
        out += std::format("#pragma once\n\n");
        out += std::format("#include <cstdint>\n\n");
        out += std::format("namespace rey_engine::generated {{\n\n");

        for (size_t i = 0; i < soa_data.names.size(); ++i) {
            const auto& name = soa_data.names[i];
            const uint32_t set = soa_data.sets[i];
            const uint32_t binding = soa_data.bindings[i];

            out += std::format("    constexpr uint32_t SET_{} = {};\n", name, set);
            out += std::format("    constexpr uint32_t BINDING_{} = {};\n\n", name, binding);
        }

        out += std::format("    // 実行時にVulkanのレイアウトを組むための静的配列など\n");
        out += std::format("    constexpr uint32_t TOTAL_BINDINGS = {};\n\n", soa_data.names.size());

        out += std::format("}}  // namespace rey_engine::generated\n");

        return out;
    }

}  // namespace vanta::slang_generator
